version: 2.1
jobs:
  build-openvisus:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - checkout
      - run:
          name: Testing arm 64
          command: |
            docker run --rm nsdf/manylinux2014_aarch64:latest uname -m
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-openvisus
